import type { post } from "../interfaces/interfaces";
import {userArray} from "./user";

export const postArray: post[] = [
  { user: userArray[0], image: "https://www.agrolink.com.br/upload/imagens-resizes/a766b2fcf5234ce781529355fc3c5c61_1200x800.jpg", 
    desc: "Plantei minhas primeiras mudas de tomate hoje!", likes: 45, date: new Date("2025-05-01") },
  { user: userArray[1], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhZIRWtmMgUBQ4PYwKO1_Im_1SZZKN8AEjqA&s", 
    desc: "Adubei as minhas rosas, estão ficando lindas.", likes: 60, date: new Date("2025-05-03") },
  { user: userArray[2], image: "https://static.wixstatic.com/media/90230e_0b16fad7a0dd4b10aaa31ea7d1b37ce0~mv2.jpg/v1/fill/w_980,h_654,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/90230e_0b16fad7a0dd4b10aaa31ea7d1b37ce0~mv2.jpg",
    desc: "Hora da rega diária. As suculentas estão amando.", likes: 32, date: new Date("2025-05-05") },
  { user: userArray[3], image: "https://pedraopedras.com.br/wp-content/uploads/2022/12/infografico-5-dicas-evitar-pragas-01.png",
    desc: "Dicas para combater pragas nas plantas sem agrotóxicos.", likes: 80, date: new Date("2025-05-06") },
  { user: userArray[4], image: "https://www.odairplantas.com.br/assets/img/produtos/412.jpg",
    desc: "Hoje foi dia de podar as hortênsias. Crescendo fortes!", likes: 55, date: new Date("2025-05-08") },
  { user: userArray[5], image: "https://weflores.com/wp-content/uploads/Orquidea-phalaenopsis-reta-variada.jpg",
    desc: "Minhas orquídeas começaram a florescer. Que alegria!", likes: 120, date: new Date("2025-05-10") },
  { user: userArray[6], image: "https://assets.brasildefato.com.br/2024/09/image_processing20200201-29235-19qx097.jpg",
    desc: "Transformei meu quintal em uma pequena horta urbana.", likes: 210, date: new Date("2025-05-12") },
  { user: userArray[7], image: "https://www.embrapa.br/image/journal/article?img_id=38911264&t=1540906287107",
    desc: "Testando um novo fertilizante orgânico nas minhas plantas.", likes: 75, date: new Date("2025-05-14") },
  { user: userArray[8], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS01hObBzOnYXA7W9nUN_eJsOMUaigpqS4ZGQ&s",
    desc: "Como fazer compostagem caseira para nutrir seu jardim.", likes: 90, date: new Date("2025-05-15") },
  { user: userArray[9], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq546J-2_2TNuKPILrOSRbLoi9hUIiAObCrg&s",
    desc: "A beleza das samambaias sempre me encanta!", likes: 38, date: new Date("2025-05-17") },
  { user: userArray[10], image: "https://projetodemae.com/wp-content/uploads/2025/05/O-jeito-pratico-de-plantar-ervas-na-varanda-e-usar-o-ano-inteiro-com-dicas-essenciais-para-seu-cultivo-750x430.jpg.webp",
    desc: "Ervas aromáticas fresquinhas direto da varanda!", likes: 67, date: new Date("2025-05-18") },
  { user: userArray[11], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc0FW14EQmOaEkGLyX2u-h_c1ugsNRWFaSzw&s",
    desc: "Segredo para as violetas florescerem o ano inteiro.", likes: 95, date: new Date("2025-05-20") },
  { user: userArray[12], image: "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia16518/sistema-de-irrigacao-caseiro-como-montar.jpg",
    desc: "Instalei um sistema de irrigação automatizado!", likes: 110, date: new Date("2025-05-22") },
  { user: userArray[13], image: "https://www.odairplantas.com.br/assets/img/produtos/234.jpg",
    desc: "Replantei minhas mudas de manjericão hoje.", likes: 50, date: new Date("2025-05-23") },
  { user: userArray[14], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0VGjaLLrnXZZuKvEWw8WrhlLlkR8u6va8sg&s",
    desc: "Como escolher o vaso ideal para cada planta.", likes: 42, date: new Date("2025-05-25") },
  { user: userArray[15], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-EDFtJE5sPVCvIiGbjuuVCJSU44FpQtY8tA&s",
    desc: "A importância da luz natural para o desenvolvimento das plantas.", likes: 78, date: new Date("2025-05-27") },
  { user: userArray[16], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdCqYG8gFC8t-TsgdzPL8mfNQdF7LfcUdhGA&s",
    desc: "Hoje plantei girassóis no jardim. Mal posso esperar que floresçam!", likes: 100, date: new Date("2025-05-28") },
  { user: userArray[17], image: "https://cdn.slidesharecdn.com/ss_thumbnails/controlenatural-110621225739-phpapp01-thumbnail.jpg?width=640&height=640&fit=bounds",
    desc: "Controle natural de insetos com calda de fumo.", likes: 64, date: new Date("2025-05-30") },
  { user: userArray[18], image: "https://www.uepg.br/wp-content/uploads/2025/04/Plantacao-de-cobertura-fazenda-escola-Tierri-Angeluci-baixa-2-scaled.jpg",
    desc: "Preparando o solo para o plantio de inverno.", likes: 85, date: new Date("2025-06-01") },
  { user: userArray[19], image: "https://a-static.mlcdn.com.br/800x560/jardim-vertical-madeira-80x60-modular-1-unid-horta-trelica-artezano/oliststore/mgll1svlyiflj5dm/d71e12431e1aebe38e8b0092ec7b5891.jpeg",
    desc: "Aproveitei o dia ensolarado para reorganizar meu jardim vertical.", likes: 93, date: new Date("2025-06-02") }
];